USE SISTEMA_PEDIDOS
--FAZER UMA QUERY NA TABELA TB_EMPREGADO
SELECT *
FROM TB_EMPREGADO

--POPULAR TABELA COM INSERT DECLARATIVO
--TESTAR A REGRA DE FK-FOREING KEY DA COLUNA COD_DEPTO
INSERT INTO TB_EMPREGADO(CODFUN,NOME,NUM_DEPEND,DATA_NASCIMENTO,COD_DEPTO,COD_CARGO,
						 DATA_ADMISSÃO,SALARIO,PREMIO_MENSAL,SINDICALIZADO,OBS,FOTO,COD_SUPERVISOR,CPF)
VALUES(1, 'OLAVO TRINDADE',4, '1950/10/05', 4, 2, 
		  '1986/06/10', 3000, 1200, 'S', 'N/A', 'N/A', 1, 14557535894)

SELECT *
FROM TB_EMPREGADO
