USE SISTEMA_PEDIDOS
--CONSTRAINT CHECK NA COLUNA SINDICALIZADO
--SINDICALIZADO SÓ PODERA RECEBER S OU N
ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT CK_EMPREGADO_SIND CHECK(SINDICALIZADO IN ('S', 'N'))

EXEC SP_HELP TB_EMPREGADO

--CONSTRAINT DEFAULT
--COLUNA SINDICALIZADA RECEBERA POR PADRÃO S
/*
ALTER TABLE <NOME_TABELA>
ADD
CONSTRAINT <NOME_INTERNO_REGRA> DEFAULT('DADO') FOR <NOME DA COLUNA>
*/

ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT DF_EMPREGADO_SIND DEFAULT('S') FOR SINDICALIZADO

EXEC SP_HELP TB_EMPREGADO