USE SISTEMA_PEDIDOS
--TABELAS EXISTENTES NO BANCO EM USO
SELECT *
FROM SYS.TABLES
--CRIAR A TABELA TB_CARGO
CREATE TABLE TB_CARGO
(COD_CARGO INT NOT NULL 
,CARGO VARCHAR(30) NOT NULL
,SALARIO_INIC FLOAT NOT NULL
,CONSTRAINT PK_CODCARGO PRIMARY KEY (COD_CARGO)
)

--VISUALIZAR A ESTRUTURA DA TABELA
EXEC SP_HELP TB_CARGO