USE SISTEMA_PEDIDOS
--SINTAXE DE CHAVE ESTRANGEIRA
/*
CONSTRAINT <NOME_FK> FOREIGN KEY (CAMPO)
REFERENCES <NOME_TABELA>(CAMPO-CHAVE PRIMARIA)
*/
--COD_DEPTO
--COD_CARGO
ALTER TABLE TB_EMPREGADO
ADD 
CONSTRAINT FK_CODDEPTO FOREIGN KEY (COD_DEPTO)
REFERENCES TB_DEPARTAMENTO(COD_DEPTO)

ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT FK_CODCARGO FOREIGN KEY(COD_CARGO)
REFERENCES TB_CARGO(COD_CARGO)