USE SISTEMA_PEDIDOS
/*
SINTAXE DO COMANDO DE CRIAR TABELA
CREATE TABLE <NOME_TABELA>
(
DECLARAR OS CAMPOS E TIPOS DE DADOS
)
*/
--CRIAR TABELA DE DEPARTAMENTO
CREATE TABLE TB_DEPARTAMENTO
(COD_DEPTO INT PRIMARY KEY
,DEPTO VARCHAR (25) NOT NULL
)
--VERIFICAR A ESTRUTURA DA TABELA
EXEC SP_HELP TB_DEPARTAMENTO
--CONSULTAROS REGISTROS DE UMA TABELA
--SELECT
/*
SELECT <CAMPOS> 
FROM <NOME_TABELAS>
*/

SELECT *
FROM TB_DEPARTAMENTO