--DELETE COM JOIN

--APAGAR AS VENDAS DO VENDEDOR MARCELO 2016/16/12 A 2016/31/12

BEGIN TRAN

DELETE 
FROM TB_PEDIDO_TEMP
OUTPUT DELETED.*
FROM TB_PEDIDO_TEMP AS PED
INNER JOIN TB_VENDEDOR AS VEND
ON PED.CODVEN=VEND.CODVEN
WHERE PED.DATA_EMISSAO BETWEEN '2016/16/12' AND '2016/31/12'
AND VEND.NOME='MARCELO'

ROLLBACK

