--DELETE COM SUBQUERY
--APAGAR REGISTROS DAS VENDAS DO VENDEDOR MARCELO 2016/12/01 A 2016/12/15
--CRIAR UMA COPIA DA TB_PEDIDO
SELECT *
INTO TB_PEDIDO_TEMP
FROM TB_PEDIDO

SELECT *
FROM TB_PEDIDO_TEMP

BEGIN TRAN

DELETE 
FROM TB_PEDIDO_TEMP
OUTPUT deleted.*
WHERE DATA_EMISSAO BETWEEN '2016/01/12' AND '2016/15/12'
   AND CODVEN=(SELECT CODVEN
               FROM TB_VENDEDOR
               WHERE NOME='MARCELO')

ROLLBACK

COMMIT