--LISTAR O NOME DO FUNCIONARIO, SALARIO E O SALARIO INICIAL (TB_CARGO)
SELECT CODFUN
	  ,NOME
	  ,COD_CARGO
	  ,SALARIO
	  ,(SELECT SALARIO_INIC
	    FROM TB_CARGO
		WHERE COD_CARGO=TB_EMPREGADO.COD_CARGO) AS SALARIO_INICIAL
FROM TB_EMPREGADO

--OU

SELECT CODFUN
	  ,NOME
	  ,COD_CARGO
	  ,SALARIO
	  ,(SELECT SALARIO_INIC
	    FROM TB_CARGO
		WHERE COD_CARGO=EMP.COD_CARGO) AS SALARIO_INICIAL
FROM TB_EMPREGADO AS EMP


--EXIBIR TOTAL VENDIDO POR VENDEDOR NO PERIODO DE 01/2016 E REALIZAR O CALCULO TOTAL EM RELAÇÃO AO TOTAL DE VENDAS

SELECT PED.CODVEN
	  ,VEND.NOME AS NOME_VENDEDOR
	  ,SUM (PED.VLR_TOTAL) AS TOTAL
	  ,(SELECT SUM(VLR_TOTAL)
	   FROM TB_PEDIDO
	   WHERE DATA_EMISSAO BETWEEN '2016/01/01' AND '2016/31/01')/SUM (PED.VLR_TOTAL)*100 AS PERCENTUAL 
FROM TB_PEDIDO AS PED
INNER JOIN TB_VENDEDOR AS VEND
ON PED.CODVEN=VEND.CODVEN
WHERE YEAR(PED.DATA_EMISSAO)=2016
GROUP BY PED.CODVEN, VEND.NOME
