--SUBQUERY NA CLAUSULA FROM
--EXIBIR NUMERO DO PEDIDO, DATA_EMISSAO, VLR_TOTAL, MAS OMENTE DE 2016

SELECT *
FROM (SELECT NUM_PEDIDO
	  ,DATA_EMISSAO
	  ,VLR_TOTAL
       FROM TB_PEDIDO
       WHERE YEAR(DATA_EMISSAO) = 2016) AS TABELA_VENDAS2016
WHERE TABELA_VENDAS2016.VLR_TOTAL > 5000
ORDER BY VLR_TOTAL

