--SUBQUERY COM IN E NOT IN

--LISTAR OS FUNCIONARIOS ONDE O CARGO TENHA SALARIO INICIAL < 5000
SELECT NOME, COD_CARGO
FROM TB_EMPREGADO
WHERE COD_CARGO IN (SELECT COD_CARGO
                 FROM TB_CARGO
                 WHERE SALARIO_INIC<5000)
ORDER BY COD_CARGO

--LISTAR OS DEPARTAMENTOS QUE NÃO EXISTE NENHUM FUNCIONARIO CADASTRADO
SELECT *
FROM TB_DEPARTAMENTO
WHERE COD_DEPTO NOT IN (SELECT COD_DEPTO
                        FROM TB_EMPREGADO
                        WHERE COD_DEPTO IS NOT NULL)

--LISTAR OS CARGOS QUE NÃO EXISTE NENHUM FUNCIONARIO ASSOSCIADO A ELES NA TB_EMPREGADO
SELECT COD_CARGO, CARGO
FROM TB_CARGO
WHERE COD_CARGO NOT IN (SELECT COD_CARGO
                        FROM TB_EMPREGADO
                        WHERE COD_CARGO IS NOT NULL)