USE PEDIDOS

--UPDATE--ATUALIZAR OS DADOS DA TABELA
--FAZER COPIA DA TB_EMPREGADO-->EMPREGADO_EMP
SELECT *
INTO EMPREGADO_TEMP
FROM TB_EMPREGADO

SELECT *
FROM EMPREGADO_TEMP

--ATUALIZAR EM 20% O SALARIO DOS FUNCIONARIOS DO DEPARTAMENTO  2
SELECT *
FROM EMPREGADO_TEMP
WHERE COD_DEPTO =2

UPDATE EMPREGADO_TEMP
SET SALARIO= SALARIO * 1.2

DROP TABLE EMPREGADO_TEMP

SELECT *
INTO EMPREGADO_TEMP
FROM TB_EMPREGADO

SELECT *
FROM EMPREGADO_TEMP
WHERE COD_DEPTO =2

--ABRIR UMA TRANSAÇÃO
BEGIN TRANSACTION
SELECT @@TRANCOUNT
UPDATE EMPREGADO_TEMP
SET SALARIO=SALARIO *1.2
WHERE COD_DEPTO=2
ROLLBACK TRANSACTION --VOLTA A TRASAÇÃO (DESFAZ O UPDATE)

--CERTEZA DA EXECUÇÃO DO COMANDO ENTÃO EFETIVAR O COMANDO
COMMIT TRANSACTION
