--QUERY DINAMICA -->RECEBENDO VALOR DE UMA QUERY
--ARMAZENAR A QUERY ABAIXO EM UMA VARIÁVEL
DECLARE @SQL VARCHAR(300)
SET @SQL='SELECT * FROM TB_PRODUTO'
--EXECUTAR A VARIAVEL @SQL QUE CONTEM A QUERY
EXEC(@SQL)