SELECT NOME
FROM TB_EMPREGADO

--SCRIPT PARA LER O NOME DO FUNCIONARIO, MAS RETORNAR APENAS O PRIMEIRO NOME


SELECT *
INTO EMPREGADO_TEMP
FROM TB_EMPREGADO

UPDATE EMPREGADO_TEMP
SET NOME='OLAVO'
WHERE CODFUN=1

SELECT NOME
	  ,CHARINDEX(' ',NOME) AS POSICAO
	  ,SUBSTRING(NOME, 1, CHARINDEX(' ',NOME))
FROM EMPREGADO_TEMP
---------------------------------------------------------------
DECLARE @CODEMP INT
	   ,@NOME CHAR(10)
SET @CODEMP=5
SELECT @NOME=SUBSTRING(NOME, 1, CHARINDEX(' ',NOME))
FROM EMPREGADO_TEMP
WHERE CODFUN=@CODEMP
SELECT @NOME AS PRIMEIRO_NOME

--EXIBIR NOME QUANDO A POSIÇÃO DO ESPAÇO FOR IGUAL A ZERO
DECLARE @CODEMP INT
	   ,@NOME CHAR(10)
SET @CODEMP=1
SELECT @NOME=CASE CHARINDEX(' ',NOME)
				WHEN 0 THEN NOME
				ELSE SUBSTRING(NOME, 1, CHARINDEX(' ',NOME))
				END
FROM EMPREGADO_TEMP
WHERE CODFUN=@CODEMP
SELECT @NOME AS PRIMEIRO_NOME

