--SCRIPT COM VARIAVEL E CASE
DECLARE @DATA DATE
       ,@DIA INT
SET @DATA='2024/01/11'
SET @DIA=DATEPART(WEEKDAY, @DATA)
PRINT @DIA
SELECT CASE @DIA
        WHEN 1 THEN 'DOMINGO'
        WHEN 2 THEN 'SEGUNDA-FEIRA'
        WHEN 3 THEN 'TERÇA-FEIRA'
        WHEN 4 THEN 'QUARTA-FEIRA'
        WHEN 5 THEN 'QUINTA-FEIRA'
        WHEN 6 THEN 'SEXTA-FEIRA'
        WHEN 7 THEN 'SABADO'
    END AS DIA_SEMANA