USE SISTEMA_PEDIDOS

SELECT *
FROM TB_EMPREGADO

--INDICE-->CRIAR INDICE PARA COLUNA CPF COM NOME NDX_CPF TA TB_EMPREGADO
CREATE NONCLUSTERED INDEX NDX_CPF
ON TB_EMPREGADO(CPF)

--VISUALIZAR INDICE CRIADO
EXEC SP_HELP TB_EMPREGADO

SELECT *
FROM TB_EMPREGADO
WHERE CPF=34523343454

--CRIAR INDICE EM UMA VISÃO
CREATE VIEW VW_EMPREGADO
WITH SCHEMABINDING
AS
SELECT CODFUN
	  ,NOME
	  ,DATA_ADMISSÃO
	  ,COD_CARGO
	  ,SALARIO
FROM DBO.TB_EMPREGADO

SELECT *
FROM VW_EMPREGADO

--CRIAR INDICE PARA COLUNA CODFUN NA VW_EMPREGADO
CREATE UNIQUE CLUSTERED INDEX NDX_CODFUN
ON VW_EMPREGADO(CODFUN)

EXEC SP_HELP VW_EMPREGADO

SELECT *
FROM VW_EMPREGADO
WHERE CODFUN=3

--APAGAR INDICE
DROP INDEX NDX_CODFUN ON VW_EMPREGADO





