--OPERADOR DE CONJUTO-->INTERSECT(INTERSECÇÃO)

SELECT COD_DEPTO
	  ,NOME
	  ,DATA_ADMISSAO
	  ,SALARIO
INTO TB_MAIOR_SALARIO
FROM TB_EMPREGADO
WHERE SALARIO>5000

SELECT *
FROM TB_MAIOR_SALARIO

--COMPARAR 2 COSULTAS--> TB_EMPREGADO/TB_MAIOR_SALARIO
SELECT NOME
	  ,COD_DEPTO
	  ,SALARIO
FROM TB_EMPREGADO
INTERSECT
SELECT NOME
	  ,COD_DEPTO
	  ,SALARIO
FROM TB_MAIOR_SALARIO