--MERGE 
--CRIR COPIA DA TB_EMPREGADO COM EMP_PROD (TABELA ALVO)
SELECT *
INTO EMP_PROD
FROM TB_EMPREGADO

SELECT *
FROM EMP_PROD

--APAGAR OS REGISTROS DO COD_CARGO=3 (PARA USO DIDATICO)
DELETE
FROM EMP_PROD
WHERE COD_CARGO=3

--ATUALIZAR OS REGISTROS AUMENTANDO O SALARIO DOS FUNCIONARIOS EM 10% P/ FUNCIONARIOS DO DEPTO 2
UPDATE EMP_PROD
SET SALARIO=SALARIO*1.10
WHERE COD_DEPTO=2

EXEC SP_HELP EMP_PROD

--MERGE
SET IDENTITY_INSERT EMP_PROD ON

MERGE EMP_PROD AS EMPPROD -- TABELA ALVO
USING TB_EMPREGADO AS EMP -- TABELA FONTE
ON EMPPROD.CODFUN=EMP.CODFUN

WHEN MATCHED AND EMPPROD.SALARIO<>EMP.SALARIO THEN
	 UPDATE
	 SET EMPPROD.SALARIO=EMP.SALARIO

WHEN NOT MATCHED THEN
	INSERT (CODFUN
,NOME
,NUM_DEPEND
,DATA_NASCIMENTO
,COD_DEPTO
,COD_CARGO
,DATA_ADMISSAO
,SALARIO
,PREMIO_MENSAL
,SINDICALIZADO
,OBS
,FOTO)
	VALUES (CODFUN
,NOME
,NUM_DEPEND
,DATA_NASCIMENTO
,COD_DEPTO
,COD_CARGO
,DATA_ADMISSAO
,SALARIO
,PREMIO_MENSAL
,SINDICALIZADO
,OBS
,FOTO);

SET IDENTITY_INSERT EMP_PROD OFF