--OPERADORES DE CONJUNTO--UNION E UNION ALL
--UNIR OS DADOS DE DUAS QUEREIS
SELECT NOME
FROM TB_EMPREGADO
UNION
SELECT NOME
FROM TB_VENDEDOR
----------------------------------------------

--ERRO--
--UNION CONTEM DISTINCT
--UNION UNE OS DADOS DAS CONSULTAS ELIMINANDO A DUPLICIDADE
SELECT NOME
FROM TB_EMPREGADO
UNION
SELECT NOME
FROM TB_MAIOR_SALARIO

--UNION ALL UNE OS DASOS DAS CONSULTAS, MAS NÃO ELIMINA A DUPLICIDADE
SELECT NOME
FROM TB_EMPREGADO
UNION ALL
SELECT NOME
FROM TB_MAIOR_SALARIO
ORDER BY