CREATE VIEW VW_DADOS_EMP
AS
SELECT NOME
	  ,COD_DEPTO
	  ,SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO IN(2,5,8,11)

--CONSULTAR A VIEW VW_DADOS_EMP
SELECT *
FROM VW_DADOS_EMP
ORDER BY COD_DEPTO

--CRIAR UMA VISÃO (VIEW) UNINDO DUAS TABELAS
CREATE VIEW VW_EMPREGADOS_DEPTONULL
AS
SELECT EMP.NOME
	  ,EMP.COD_DEPTO
	  ,DEPTO.DEPTO
	  ,EMP.SALARIO
FROM TB_EMPREGADO AS EMP
LEFT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO

SELECT *
FROM VW_EMPREGADOS_DEPTONULL
ORDER BY COD_DEPTO

--APAGAR VIEW
DROP VIEW VW_EMPREGADOS_DEPTONULL