USE SISTEMA_PEDIDOS
--CONSTRAINT(REGRA) CHECK
EXEC SP_HELP TB_CARGO
--CHECK PARA COLUNA SALARIO_INIC (COLUNA NÃO PODE SER NEGATIVA)
/*
SINTAXE CONSTRAINT CHECK
ALTER TABLE <NOME_TABELA>
ADD
CONSTRAINT <NOME_INTERNO_REGRA> CHECK (NOME_COLUNA <CONDIÇÃO>)
*/

ALTER TABLE TB_CARGO
ADD
CONSTRAINT CK_CARGO_SALARIOINIC CHECK(SALARIO_INIC>0)

EXEC SP_HELP TB_CARGO

--CONSTRAINT UNIQUE
--COLUNA CPF NÃO PODE REPETIR
/*
SINTAXE DA CONSTRUINT UNIQUE
ALTER TABLE <NOME_TABELA>
ADD
CONSTRAINT <NOME_INTERNO_REGRA> UNIQUE(NOME_COLUNA)
*/
ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT UQ_EMPREGADO_CPF UNIQUE(CPF)
EXEC SP_HELP TB_EMPREGADO
