USE PEDIDOS
--COLUNA CALCULADA
--NESTA QUERY EXIBIREMOS NOME DO FUNCIONARIO, SALARIO E O SALARIO CALCULADO COM AUMENTO DE 10%
SELECT NOME
	  ,SALARIO
	  ,SALARIO * 1.10 AS SALARIO_ATUAL
FROM TB_EMPREGADO

--CLAUSULA TOP
SELECT *
FROM TB_EMPREGADO

--FAZER UMA QUERY QUE LISTE OS FUNCIONARIOS MAIS ANTIGOS
SELECT TOP(10)NOME
	  ,SALARIO
	  ,DATA_ADMISSAO
FROM TB_EMPREGADO
ORDER BY DATA_ADMISSAO

