--USER DEFINED DATYPE-->TIPO DE DADOS DEFINIDO PELO USUARIO
--COLUNA ENDEREÇO CHAR(60) TAB1 E VARCHAR(100) TAB2
--CRIAR UM TIPO DE DADOS PARA A COLUNA ENDEREÇO E QTDE DE CARACTERES IGUAL A 60
CREATE TYPE TIPO_ENDERECO
FROM VARCHAR(60) NOT NULL

--VERIFICAR OS TIPOS DE DADOS DEFINIDOS PELOS USUARIOS
SELECT *
FROM SYSTYPES
WHERE UID=1

USE MASTER
CREATE DATABASE DB_USERDATATYPE
USE DB_USERDATATYPE

CREATE TYPE TIPO_NOME_PESSOA
FROM VARCHAR(40) NOT NULL

CREATE TYPE TIPO_PRECO
FROM NUMERIC(12,2) NOT NULL

CREATE TYPE TIPO_SN
FROM CHAR(1) NULL

--CRIAR TABELA PRODUTOS
CREATE TABLE PRODUTOS
(COD_PROD INT IDENTITY(1,1)
,DESCRICAO VARCHAR(80)
,PREÇO_VENDA TIPO_PRECO
,SN_ATIVO TIPO_SN
,CONSTRAINT PK_PRODUTO_COD PRIMARY KEY(COD_PROD))