--DELETE-->APAGAR REGISTROS DA TABELA

SELECT *
FROM EMPREGADO_TEMP

--APAGAR O REGISTRO DO FUNCIONARIO CODFUN=73
DELETE
FROM EMPREGADO_TEMP
WHERE CODFUN=73

--CUIDADO AO DELETAR DADOS DE UMA TABELA, POIS NÃO HÁ VOLTA. USE SEMPRE QUE POSSIVEL O BEGIN TRANSACTION
--EX: APAGAR OS REGISTROS DO DEPARTAMENTO 2

SELECT *
FROM EMPREGADO_TEMP
WHERE COD_DEPTO=2

BEGIN TRAN
DELETE
FROM EMPREGADO_TEMP
WHERE COD_DEPTO=2
ROLLBACK

--EFETIVAR A TRANSAÇÃO
COMMIT