--EXPRESSÃO CASE PESQUISADA
--SINTAXE

/*CASE
	WHEN <CONDIÇÃO_COLUNA> THEN <EXPRESSÃO>
	WHEN <CONDIÇÃO_COLUNA> THEN <EXPRESSÃO>
ELSE
	<EXPRESSÃO>
END
*/

SELECT NOME
	  ,SALARIO
	  ,CLASSIFICACAO_SALARIAL=CASE
								WHEN SALARIO IS NULL THEN 'NÃO CLASSIFICADO'
								WHEN SALARIO = 500 THEN 'SALARIO BAIXO'
								WHEN SALARIO > 500 AND SALARIO < 3000 THEN 'SALARIO MÉDIO'
							  ELSE
							    'SALARIO ALTO'
							  END

FROM TB_EMPREGADO
ORDER BY SALARIO