--EXPRESSÃO CASE-->SIMPLES E PESQUISADA

--EXPRESSÃO CASE SIMPLES: SINTAXE

/*CASE <COLUNA>
	WHEN <CONDIÇÃO> THEN <EXPRESSÃO>
	WHEN <CONDIÇÃO> THEN <EXPRESSÃO>
ELSE 
	<EXPRESSÃO>
END
*/

SELECT NOME
	  , SALARIO
	  ,SINDICALIZADO
	  ,CASE SINDICALIZADO
		  WHEN 'S' THEN 'SIM'
		  WHEN 'N' THEN 'NÃO'
	   ELSE
	     'N/C'
	   END AS SINDICATO
FROM TB_EMPREGADO


SELECT NOME
	  , SALARIO
	  ,CASE SINDICALIZADO
		  WHEN 'S' THEN 'SIM'
		  WHEN 'N' THEN 'NÃO'
	   ELSE
	     'N/C'
	   END AS SINDICALIZADO
FROM TB_EMPREGADO