--EXPRESSAO NULLIF-->COMPARAR DOIS VALORES OU COLUNAS

SELECT NULLIF (7,7) AS IGUAIS, NULLIF (55,4) AS DIFERENTE

SELECT NOME
	  ,ESTADO
	  ,EST_COB
	  ,NULLIF(ESTADO,EST_COB) AS ESTADO_ANALISE
FROM TB_CLIENTE
ORDER BY ESTADO

--FUNÇÃO COALESCE

SELECT NOME
	  ,ESTADO
	  ,EST_COB
	  ,COALESCE(ESTADO,EST_COB) AS ESTADO_ANALISE
FROM TB_CLIENTE
ORDER BY ESTADO
