USE SISTEMA_PEDIDOS
--VISUALIZAR A ESTRUTURA DA TB_EMPREGADO
EXEC SP_HELP TB_EMPREGADO
--APAGAR A COLUNA CPF
/*
SINTAXE PARA APAGAR UMA COLUNA
ALTER TABLE <NOME_TABELA>
DROP COLUMN <NOME_COLUNA>
*/

ALTER TABLE TB_EMPREGADO
DROP COLUMN CPF

--ACRESCENTAR A COLUNA CPF NOVAMENTE COM INT
--OBS: CPF POR SER UM NUMERO GRANDE DEVERIA USAR O TIPO DE DADOS BIGINT, MAS COMO É PARA FINS DIDATICOS,AQUI USAREMOS INT PARA MOSTRAR COMO FAZ UMA ALTERAÇÃO
ALTER TABLE TB_EMPREGADO
ADD
CPF INT NOT NULL

--ALTERAR TIPO DE DADO DO CPF DE INT PARA BIGINT

/*
SINTAXE PARA ALTERAR O TIPO DE DADOS DE UMA COLUNA 
ALTER TABLE <NOME_TABELA>
ALTER COLUMN <NOME_COLUNA><TIPO_DE_DADOS>
*/

ALTER TABLE TB_EMPREGADO
ALTER COLUMN CPF BIGINT NOT NULL

EXEC SP_HELP TB_EMPREGADO
