USE PEDIDOS

--FUNÇÃO COUNT -- AGRUPAMENTO

SELECT COUNT(*) AS QTDE_REGISTROS 
FROM TB_EMPREGADO


SELECT COUNT(NOME) AS QTDE_REGISTROS 
FROM TB_EMPREGADO


SELECT COUNT(COD_DEPTO) AS QTDE_REGISTROS 
FROM TB_EMPREGADO


SELECT * 
FROM TB_EMPREGADO
ORDER BY COD_DEPTO

--QUANTIDADE DE DEPARTAMENTOS NA TABELA DE EMPREGADOS SEM DUPLICIDADE
SELECT COUNT(DISTINCT COD_DEPTO) AS QTDE_REGISTROS 
FROM TB_EMPREGADO

SELECT APPROX_COUNT_DISTINCT(COD_DEPTO) AS QTDE_REGISTROS 
FROM TB_EMPREGADO

--------------------------------------------------------------------------------------------

--FUNÇÃO DE AGREGAÇÃO COM AGRUPAMENTO-GROUP BY
--EX->EXIBIR O CUSTO SALARIAL POR DEPARTAMENTO
SELECT COD_DEPTO
	  ,SUM(SALARIO) AS TOTAL_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO IS NOT NULL
GROUP BY COD_DEPTO



