--FUN플O REPLICATE-->REPLICA UMA SEQUENCIA DE CARACTERES
SELECT REPLICATE(' *-* ', 3) AS FORMA

--FUN플O REVERSE--> LE UM TEXTO DA ESQUERDA PARA DIREITA
SELECT REVERSE('AMOR') AS PALAVRA

SELECT NOME + ': ' + CAST(SALARIO AS CHAR(10)) AS NOME
FROM TB_EMPREGADO

--CONCATENA플O COM DATA
SELECT NOME + ': ' + CAST(DATA_NASCIMENTO AS CHAR(11))
FROM TB_EMPREGADO

--FUN플O CONVERT
SELECT NOME + ': ' + CONVERT(CHAR(10), DATA_NASCIMENTO, 103) AS NOME
FROM TB_EMPREGADO