--CONCATENAR-->PODE SER FEITA COM (+) OU FUNÇÃO(CONCAT)
SELECT NOME
	  ,ENDERECO+ ' & ' +CEP AS ENDERECO
FROM TB_CLIENTE

SELECT NOME
	  ,CONCAT(ENDERECO, ' & ' ,CEP) AS ENDERECO
FROM TB_CLIENTE

--LOWER(LETRA MINUSCULA)/UPPER(LETRA MAIUSCULA)
SELECT NOME
	  ,LOWER(NOME) AS NOME_MINUSCULO
FROM TB_CLIENTE

SELECT UPPER('é facil trocar palavras, dificil é interpretar o silêncio') AS LETRA