--FUN합ES DE TEXTO
--LEFT/RIGHT

SELECT *
FROM TB_CLIENTE

SELECT NOME
	  ,ENDERECO
	  ,CEP
	  ,LEFT(CEP, 5) AS REGIAO
	  ,RIGHT(CEP, 3) AS DISTRIBUI플O
FROM TB_CLIENTE

--LEN -->RETORNA A QUANTIDADE DE CARACTERES OCUPADOS EM UMA COLUNA

SELECT NOME
	  ,LEN(NOME) AS QTDE_NOME
	  ,ISNULL(CEP,'N/C') AS CEP
	  ,LEN(ISNULL(CEP, 'N/C')) AS QTDE_CEP
FROM TB_CLIENTE
ORDER BY CEP

EXEC SP_HELP TB_CLIENTE


SELECT NOME
	  ,LEN(NOME) AS QTDE_NOME
	  ,ISNULL(CEP,'N/C') AS CEP
	  ,ISNULL(LEN(CEP), 0) AS QTDE_CEP
FROM TB_CLIENTE
ORDER BY CEP


SELECT NOME
	  ,ENDERECO
	  ,CEP
	  ,LEFT(ISNULL(CEP, 'N/C'), 5) AS REGIAO
	  ,RIGHT(ISNULL(CEP, 'N/C'), 3) AS DISTRIBUI플O
FROM TB_CLIENTE
ORDER BY CEP

--SUBSTRING

SELECT NOME
	  ,ENDERECO
	  ,CEP
	  ,SUBSTRING(CEP,1,5) AS REGIAO
	  ,SUBSTRING(CEP,6,3) AS DISTRIBUI플O
FROM TB_CLIENTE
ORDER BY CEP

