--FUN합ES MATEM햀ICAS
--RAIZ QUADRADA
SELECT SQRT(25) AS RAIZ_QUADRADA
SELECT SQRT(49) AS RAIZ_QUADRADA

--FUN플O SQUARE
SELECT SQUARE(2) AS QUADRADO
SELECT SQUARE(9) AS QUADRADO

--FUN플O POWER-->(VALOR, POTENCIA)
SELECT POWER(2,3) AS VALOR_POTENCIA
SELECT POWER(2,5) AS VALOR_POTENCIA

--FUN플O ABS-->VALOR ABSOLUTO
SELECT ABS(45)AS VALOR_ABSOLUTO
SELECT ABS(-45)AS VALOR_ABSOLUTO

--FUN플O CEILING-->RETORNA O PROXIMO NUMERO INTEIRO
SELECT CEILING(149.0) AS NUMERO_INTEIRO
SELECT CEILING(149.99) AS NUMERO_INTEIRO



