USE PEDIDOS

SELECT NOME
	  ,DEPTO
	  ,SALARIO
FROM TB_EMPREGADO AS EMP
LEFT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO =DEPTO.COD_DEPTO
ORDER BY SALARIO

SELECT NOME
	  ,DEPTO
	  ,SALARIO
FROM TB_EMPREGADO AS EMP
RIGHT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO =DEPTO.COD_DEPTO
ORDER BY SALARIO

SELECT NOME
	  ,DEPTO
	  ,SALARIO
FROM TB_EMPREGADO AS EMP
FULL JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO =DEPTO.COD_DEPTO
ORDER BY SALARIO

--