--FUNÇÃO CHARINDEX-->RETORNA A POSIÇÃO DE UM CARACTERE QUE ESTAMOS BUSCANDO

SELECT CHARINDEX('PA', 'IMPALA') AS POSICAO_TEXTO

SELECT CHARINDEX('TR',NOME)AS NOME
FROM TB_EMPREGADO
ORDER BY NOME

--REPLACE-->SUBSTITUIÇÃO DE UM CARACTERE
SELECT REPLACE('GUARDA&SOL', '&', '-') AS NAME

SELECT NOME
	  ,REPLACE(SALARIO, '.', ',') AS SALARIO
FROM TB_EMPREGADO

--LTRIM/RTRIM-->FUNÇÃO PARA ELMINAR ESPAÇO EM BRANCO A ESQUERDA(LTRIM) E ESPAÇO A DIREITA(RTRIM)
SELECT ('          GUARDA-SOL') AS TEXTO
	  ,LTRIM('         GUARDA-SOL') AS TEXTO_SEM_ESPACO

SELECT ('GUARDA-         ')+'SOL' AS TEXTO
      ,RTRIM('GUARDA-        ')+'SOL' AS TEXTO_SEM_ESPACO
