--DATEDIFF-->DIFERENÇA
--DIAS VIVIDOS
SELECT DATEDIFF(DAY, '1988/12/04', GETDATE()) AS DIAS_VIVIDOS

SELECT DATEDIFF(MONTH, '1988/12/04', GETDATE()) AS MESES_VIVIDOS

SELECT DATEDIFF(YEAR, '1988/12/04', GETDATE()) AS ANOS_VIVIDOS

SELECT NOME
	  ,DATA_NASCIMENTO
	  ,DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) AS IDADE
FROM TB_EMPREGADO
ORDER BY IDADE

--FUNÇÃO EOMONTH-->RETORNAR O ULTIMO DIA DO MES D EUMA DETERMINADA DATA
SELECT EOMONTH('2023/11/10') AS DATA_ULTIMO_DIA_MES

--WEEK-->RETORNA SEMANA DO ANO
SELECT DATEPART(WEEK,GETDATE()) AS QTDE_SEMANAS

--WEEKDAY-->RETORNA O DIA DA SEMANA EM NUMERO
SELECT DATEPART(WEEKDAY, '2025/10/13') AS DIA_SEMANA



