--FUNÇÕS MATEMÁTICAS 
--FLOOR

SELECT FLOOR(1.3012) AS VALOR_INTEIRO

SELECT *
FROM TB_PRODUTO

SELECT ID_PRODUTO
	  ,DESCRICAO
	  ,PRECO_CUSTO
	  ,FLOOR(PRECO_CUSTO) AS VALOR_INTEIRO
FROM TB_PRODUTO

--PI()
SELECT PI() AS VALOR_DE_PI

--RAND()-->VALOR RANDOMICO (ALEATÓRIO
SELECT RAND() AS VALOR_RANDOMICO

--ROUND()-->ARREDONDAMENTO
SELECT ID_PRODUTO
	  ,DESCRICAO
	  ,PRECO_VENDA
	  ,ROUND(PRECO_VENDA, 2) AS PREÇO_ARREDONDADO
FROM TB_PRODUTO

SELECT ID_PRODUTO
	  ,DESCRICAO
	  ,PRECO_VENDA
	  ,FORMAT (ROUND(PRECO_VENDA, 2), '##########0.00') AS PREÇO_ARREDONDADO
FROM TB_PRODUTO
