--FUNÇÕES PARA DATA
--DATA E HORA ATUAL
SELECT GETDATE() AS DATA_HORA_ATUAL

--SOMENTE O DIA
SELECT DAY(GETDATE()) DIA_ATUAL
SELECT DAY('2023/12/09') AS DIA

--RETORNAR O MÊS
SELECT MONTH(GETDATE()) AS MES_ATUAL
SELECT MONTH('1950/07/10') AS MES

--RETORNAR O ANO 
SELECT YEAR(GETDATE()) AS ANO_ATUAL
SELECT YEAR('1950/07/10') AS ANO

SELECT NOME
	  ,DATA_NASCIMENTO
	  ,DAY(DATA_NASCIMENTO) AS DIA
	  ,MONTH(DATA_NASCIMENTO) AS MES
	  ,YEAR(DATA_NASCIMENTO) AS ANO
FROM TB_EMPREGADO

--FUNÇÃO DATENAME

SELECT NOME
	  ,DATA_NASCIMENTO
	  ,DAY(DATA_NASCIMENTO) AS DIA
	  ,MONTH(DATA_NASCIMENTO) AS MES
	  ,DATENAME(MONTH, DATA_NASCIMENTO) AS MES_EXTENSO
	  ,YEAR(DATA_NASCIMENTO) AS ANO
FROM TB_EMPREGADO

