SELECT NOME AS NOME_EMPREGADO
	  ,DEPTO AS DEPARTAMENTO
	  , SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO

SELECT NOME AS NOME_EMPREGADO
	  ,EMP.COD_DEPTO 
	  ,DEPTO AS DEPARTAMENTO
	  , SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO