USE SISTEMA_PEDIDOS

SELECT NOME AS NOME_FUNCIONARIO
      ,DEPTO AS DEPARTAMENTO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
WHERE NOME LIKE 'O%'

USE PEDIDOS

SELECT NOME AS NOME_FUNCIONARIO
      ,DEPTO AS DEPARTAMENTO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
WHERE NOME LIKE 'O%'


SELECT NOME AS NOME_FUNCIONARIO
      ,DEPTO AS DEPARTAMENTO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
ORDER BY NOME

SELECT NOME
      ,DEPTO AS NOME_DEPARTAMENTO
      ,CARGO AS NOME_CARGO
      ,SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
INNER JOIN TB_CARGO AS CARGO
ON EMP.COD_CARGO=CARGO.COD_CARGO

SELECT NOME
      ,DEPTO AS NOME_DEPARTAMENTO
      ,CARGO AS NOME_CARGO
      ,SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
INNER JOIN TB_CARGO AS CARGO
ON EMP.COD_CARGO=CARGO.COD_CARGO
WHERE DEPTO IN ('COMPRAS','PRODUCAO')
