USE SISTEMA_PEDIDOS

--COLOCAR EM USO O BANCO DE DADOS (PEDIDOS)
USE PEDIDOS
SELECT *
FROM TB_CARGO

--VOLTAR PARA O BANCO DE DADOS SISTEMAS_PEDIDOS
USE SISTEMA_PEDIDOS
SELECT *
FROM TB_CARGO

--INSERIR OS REGISTROS DA TABELA DE TB_CARGO PEDIDOS NA TB_CARGO SISTEMA_PEDIDOS
INSERT INTO TB_CARGO(COD_CARGO, CARGO, SALARIO_INIC)
SELECT COD_CARGO, CARGO, SALARIO_INIC
FROM PEDIDOS..TB_CARGO
WHERE COD_CARGO>6

SELECT *
FROM TB_CARGO
----------------------------------------------------------------------------------------------

--CRIAR TABELA COM O NOME TB-CLIENTE
CREATE TABLE TB_CLIENTE
(CODCLI INT PRIMARY KEY
,NOME CHAR(50)
,ESTADO CHAR(2)
)

SELECT *
FROM TB_CLIENTE

--CLAUSULA TOP
TRUNCATE TABLE TB_CLIENTE
INSERT INTO TB_CLIENTE(CODCLI, NOME, ESTADO)
SELECT CODCLI, NOME, ESTADO
FROM PEDIDOS..TB_CLIENTE

INSERT TOP (10)INTO TB_CLIENTE(CODCLI, NOME, ESTADO)
SELECT CODCLI, NOME, ESTADO
FROM PEDIDOS..TB_CLIENTE
SELECT *
FROM TB_CLIENTE

SELECT *
FROM PEDIDOS..TB_CLIENTE
--INSERIR OS REGISTROS DO ESTADO DE 'SC 'NA TABELA TB_CLENTE
INSERT INTO TB_CLIENTE(CODCLI, NOME, ESTADO)
SELECT CODCLI, NOME, ESTADO
FROM PEDIDOS..TB_CLIENTE
WHERE ESTADO='SC'

SELECT *
FROM TB_CLIENTE
