USE SISTEMA_PEDIDOS
--POPULAR A TABELA TB_CARGO COM INSERT POSICIONAL
SELECT *
FROM TB_CARGO
/*
SINTAXE
INSERT INTO TB_CARGO
VALUES(DECLARAR AS INFORMAÇÕES DE CADA COLUNA RESPEITANDO A ORDEM DE CRIAÇÃO DA TABELA)
*/
INSERT INTO TB_CARGO
VALUES(1,'SPERVISORA COMERCIAL',8500)

SELECT *
FROM TB_CARGO

--INSERT POSICIONAL PODE-SE INSERIR MAIS DE UM REGISTRO NA TABELA
INSERT INTO TB_CARGO
VALUES(2, 'QUALIDADE',2500)
	 ,(3, 'DIRETOR',12000)
	 ,(4, 'COMPRADOR', 1000)

SELECT *
FROM TB_CARGO