USE PEDIDOS

SELECT *
FROM TB_EMPREGADO
ORDER BY COD_DEPTO

SELECT NOME
	  ,DEPTO
	  ,SALARIO
FROM TB_EMPREGADO AS EMP 
LEFT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
ORDER BY EMP.COD_DEPTO

SELECT NOME
	  ,CARGO
	  ,SALARIO
FROM TB_EMPREGADO AS EMP 
LEFT JOIN TB_CARGO AS CARGO
ON EMP.COD_CARGO=CARGO.COD_CARGO
ORDER BY EMP.COD_CARGO
