USE PEDIDOS
--OPERADORES LÓGICOS
/*
AND --> COMBINA DUAS EXPRESSÕES E EXIGE QUE SEJAM VERDADEIRAS PARA QUE O REGISTRO SEJA APRESENTADO
OR --> COMBINA DUAS EXPRESSÕES E EXIGE QUE PELO MENOS UMA SEJA VERDADEIRA PARA QUE O REGISTRO SEJA APRESENTADO
NOT --> INVERTE O RESULTADO LÓGICO DA EXPRESSÃO À DIREITA
*/

SELECT COD_DEPTO
	  ,NOME
	  ,SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO=2 AND SALARIO>5000


SELECT COD_DEPTO
	  ,NOME
	  ,SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO=2 OR SALARIO>5000
ORDER BY COD_DEPTO


SELECT *
FROM TB_EMPREGADO
WHERE COD_DEPTO=3