USE PEDIDOS

SELECT NOME
	  ,SALARIO
FROM TB_EMPREGADO
ORDER BY NOME

--ORDENAR POR POSIÇÃO
SELECT NOME
	  ,SALARIO
FROM TB_EMPREGADO
ORDER BY 1

--ORDENAR SALARIO EM ORDEM DECRESCENTE
SELECT NOME
	  ,SALARIO
FROM TB_EMPREGADO
ORDER BY 2 DESC

--ORDENAR POR DUAS COLUNAS/CAMPOS
--FAZER UMA QUERY PARA RETORNAR O CODDEPTO, NOME E SALARIO
SELECT COD_DEPTO
	  ,NOME
	  ,SALARIO
FROM TB_EMPREGADO
ORDER BY COD_DEPTO, SALARIO DESC