USE PEDIDOS

SELECT *
FROM TB_EMPREGADO
ORDER BY NOME

--EXIBIR FUNCIONARIOS COM NOME INCIANDO COM 'C'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'C%'

SELECT NOME 
FROM TB_EMPREGADO
WHERE NOME LIKE 'MARIA%'

SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%SILVA'
