USE PEDIDOS

SELECT NOME
      ,DEPTO
      ,SALARIO
FROM TB_EMPREGADO AS EMP 
RIGHT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_CARGO=DEPTO.COD_DEPTO
ORDER BY SALARIO

SELECT NOME
      ,CARGO
      ,SALARIO
FROM TB_EMPREGADO AS EMP 
RIGHT JOIN TB_CARGO AS CARGO
ON EMP.COD_CARGO=CARGO.COD_CARGO
ORDER BY SALARIO

