--SINONIMO PARA O NOME DE TABELA
CREATE TABLE CAD_FUNCIONARIO
(ID INT
,NOME VARCHAR(20)
,SEXO CHAR(1)
,DATA_NASC DATETIME
)

--CRIAR UM SINONIMO -->SYNONYM
CREATE SYNONYM TAB_EMPREGADO FOR DBO.CAD_FUNCIONARIO

SELECT *
FROM TAB_EMPREGADO

SELECT *
FROM CAD_FUNCIONARIO

INSERT INTO CAD_FUNCIONARIO
VALUES(1, 'MARIO QUINTANA', 'M', '1945/03/02')

--COLUNAS COMPUTADAS

SELECT *
FROM TB_EMPREGADO

SELECT NOME
	  ,DATA_NASCIMENTO
	  ,FLOOR(CAST(GETDATE()-DATA_NASCIMENTO AS FLOAT)/365.25) AS IDADE
FROM TB_EMPREGADO

--ACRESCENTAR A COLUNA IDADE COM A FORMULA QUE CALCULA A IDADE
ALTER TABLE TB_EMPREGADO
ADD IDADE
AS FLOOR(CAST(GETDATE()-DATA_NASCIMENTO AS FLOAT)/365.25)

SELECT NOME
	  ,IDADE
	  ,DATA_NASCIMENTO
FROM TB_EMPREGADO

