USE PEDIDOS
--SINTAXE DO SELECT
/*
SELECT <NOME_COLUNA(S)>
FROM <NOME_TABELA>
WHERE <CONDIÇÃO>
GROUP BY <NOME_COLUNA(S)>
HABING <CONDIÇÃO>
ORDER BY <NOME_COLUNA(S)>
*/

--QUERY DE RETORNO DE TODAS COLUNAS TB_EMPREGADO
SELECT *
FROM TB_EMPREGADO

--ESPECIFICAR O NOME DAS COLUNAS QUE QUEREMOS VISUALIZAR NA QUERY
SELECT NOME
	  ,SALARIO
FROM TB_EMPREGADO

--CASO EU QUEIRA FAZER A MESMA CONSULTA, MAS COM OS NOMES EM ORDEM CRESCENTE OU ASCENDENTE
SELECT NOME
	  ,SALARIO
FROM TB_EMPREGADO
ORDER BY NOME ASC

--CASO EU QUEIRA FAZER A MESMA CONSULTA, MAS COM OS NOMES EM ORDEM DECRESCENTE OU DESCENDENTE
SELECT NOME
	  ,SALARIO
FROM TB_EMPREGADO
ORDER BY NOME DESC