--SUBQUERY OU SUBCONSULTA 

--MEDIA SALARIAL
SELECT AVG(SALARIO) 
FROM TB_EMPREGADO

--SALARIOS MAIORES QUE A MEDIA
SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO > (SELECT AVG(SALARIO)
                FROM TB_EMPREGADO)

------------------------------------------------------------------------------
SELECT MIN(SALARIO)
FROM TB_EMPREGADO

SELECT NOME
      ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO = (SELECT MIN(SALARIO)
                 FROM TB_EMPREGADO)