SELECT *
FROM TB_EMPREGADO

SELECT SUM(VLR_TOTAL)
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO)=2016


SELECT NUM_PEDIDO
      ,DATA_EMISSAO
      ,VLR_TOTAL
      ,(SELECT SUM(VLR_TOTAL)
        FROM TB_PEDIDO
        WHERE YEAR(DATA_EMISSAO)=2016) AS TOTAL_VENDAS_2016
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO)=2016

--ARMAZENAR O RESULTADO DA QUERY ACIMA EM UMA TABELA COM O NOME TOTATL_VENDAS_2016

SELECT NUM_PEDIDO
      ,DATA_EMISSAO
      ,VLR_TOTAL
      ,(SELECT SUM(VLR_TOTAL)
        FROM TB_PEDIDO
        WHERE YEAR(DATA_EMISSAO)=2016) AS TOTAL_VENDAS2016
INTO TOTAL_VENDAS2016
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO)=2016

SELECT NUM_PEDIDO
      ,DATA_EMISSAO
      ,VLR_TOTAL
      ,VLR_TOTAL/TOTAL_VENDAS2016 AS PERCENTUAL
FROM TOTAL_VENDAS2016

