--SELF JOIN -->AUTORELACIONAMENTO

SELECT CODFUN
	  ,NOME
	  ,COD_SUPERVISOR
FROM TB_EMPREGADO

/*
OLAVO -- LUCIO MITSUI
JOSE REIS -- SEBASTIÃO SILVA
MARCELO SOARES -- ANA MARIA OLIVEIRA
*/

SELECT EMP.NOME AS NOME_FUNCIONARIO
	  ,SUPERIOR.NOME AS NOME_SUPERIOR
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_EMPREGADO AS SUPERIOR
ON EMP.COD_SUPERVISOR=SUPERIOR.CODFUN

