--SEQUENCE
CREATE SEQUENCE SEQ_PESSOA
START WITH 1000
INCREMENT BY 10
MINVALUE 10
MAXVALUE 10000
CYCLE CACHE 3

--VERIFICARA SEQUENCIA CRIADA
SELECT *
FROM SYS.sequences

CREATE TABLE TB_PESSOA
(COD_PESSOA INT
,NOME_PESSOA VARCHAR(50))

INSERT INTO TB_PESSOA(COD_PESSOA,NOME_PESSOA)
VALUES(NEXT VALUE FOR DBO.SEQ_PESSOA, 'JOAO CARLOS')


INSERT INTO TB_PESSOA(COD_PESSOA,NOME_PESSOA)
VALUES(NEXT VALUE FOR DBO.SEQ_PESSOA, 'BEATRIZ')

INSERT INTO TB_PESSOA(COD_PESSOA,NOME_PESSOA)
VALUES(NEXT VALUE FOR DBO.SEQ_PESSOA, 'HELENA')

SELECT *
FROM TB_PESSOA