USE SISTEMA_PEDIDOS
-- FAZER UMA QUERY NA TB_DEPENDENTE
SELECT *
FROM TB_DEPENDENTE

--VISUALIZAR ESTRUTURA DA TB_DEPENDENTE
EXEC SP_HELP TB_DEPENDENTE

--INSERIR REGISTRO NA TB_DEPENDENTE
INSERT INTO TB_DEPENDENTE(CODFUN, NOME, DATA_NASCIMENTO)
VALUES(1, 'PEDRO', '1987/01/10')

INSERT INTO TB_DEPENDENTE(CODFUN, NOME, DATA_NASCIMENTO)
VALUES(2, 'CARLOS', '1988/10/01')

INSERT INTO TB_DEPENDENTE(CODFUN, NOME, DATA_NASCIMENTO)
VALUES(2, 'ALBERTO', NULL)

--REGISTRO CORRETO
INSERT INTO TB_DEPENDENTE(CODFUN, NOME, DATA_NASCIMENTO)
VALUES(2, 'ALBERTO', '1990/07/07')

SELECT *
FROM TB_DEPENDENTE