USE SISTEMA_PEDIDOS
--VISUALIZAR A ESTRUTURA DE TB_DEPARTAMENTO
EXEC SP_HELP TB_DEPARTAMENTO
SELECT *
FROM TB_DEPARTAMENTO

--INSERT DECLARATIVO
--CHAVE DUPLICADA
INSERT INTO TB_DEPARTAMENTO(COD_DEPTO,DEPTO)
VALUES(4, 'PRODU플O')

--SCRIPT CORRETO
INSERT INTO TB_DEPARTAMENTO(COD_DEPTO,DEPTO)
VALUES(5, 'PRODU플O')

SELECT *
FROM TB_DEPARTAMENTO

--TESTAR O COD_CARGO NA TB_CARGO
SELECT *
FROM TB_CARGO

INSERT INTO TB_CARGO(COD_CARGO,CARGO,SALARIO_INIC)
VALUES(5, 'VENDEDOR', 500)
--VISUALIZAR A ESTRUTURA DA TB_CARGO
EXEC SP_HELP TB_CARGO
--TESTAR A CONSTRAINT DE CHECK NA COLUNA SALARIO_INIC
--INSERT POSICIONAL
INSERT INTO TB_CARGO
VALUES(6, 'REPRESENTANTE DA DIRE플O', -900)

--SCRIPT CORRETO
--SALARIO>0
INSERT INTO TB_CARGO
VALUES(6, 'REPRESENTANTE DA DIRE플O', 900)

SELECT *
FROM TB_CARGO
