--CRIAR A TABELA TB_EMPREGADO
--CONSTRAINT DE CHAVE PRIMARIA PARA A COLUNA CODFUN
--CONSTRAINT DE COD_DEPTO E COD_CARGO
USE SISTEMA_PEDIDOS
CREATE TABLE TB_EMPREGADO
(CODFUN INT NOT NULL
,NOME VARCHAR(35) NOT NULL
,NUM_DEPEND SMALLINT NOT NULL
,DATA_NASCIMENTO DATETIME NOT NULL
,COD_DEPTO INT NOT NULL
,COD_CARGO INT NOT NULL
,DATA_ADMISSÃO DATETIME NOT NULL
,SALARIO NUMERIC (18,2) NOT NULL
,PREMIO_MENSAL NUMERIC (10,2) NOT NULL
,SINDICALIZADO CHAR(1) NOT NULL
,OBS TEXT NOT NULL
,FOTO IMAGE NOT NULL
,COD_SUPERVISOR INT NOT NULL
)
--CRIEI A PK DEPOIS, POIS CRIEI A TB SEM ESPECIFICAR 

ALTER TABLE TB_EMPREGADO
ADD CONSTRAINT PK_CODFUN PRIMARY KEY (CODFUN)
EXEC SP_HELP TB_EMPREGADO
