--CRIAR VARIAVEL-->(@)

--DECLARAR VARIÁVEL
DECLARE @VALOR INT 
--ATRIBUIR VALOR À VARIÁVEL
SET @VALOR=10
--VISUALIZAR O CONTEDO DA VARIÁVEL
PRINT @VALOR

--OU
DECLARE @VALOR2 INT
SET @VALOR2=20
SELECT @VALOR2 AS VALOR

DECLARE @NUM1 INT
	   ,@NUM2 INT
SET @NUM1=10
SET @NUM2=8
PRINT @NUM1 + @NUM2

DECLARE @CODFUN INT
SET @CODFUN=5
SELECT NOME
FROM TB_EMPREGADO
WHERE CODFUN=@CODFUN