USE PEDIDOS

SELECT *
FROM TB_EMPREGADO
ORDER BY SALARIO

--IS NULL-->RETORNA NULABILIDADE
SELECT NOME
	  ,CODFUN
	  ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO IS NULL

--IS NOT NULL-->NEGA NULABILIDADE
SELECT NOME
	  ,CODFUN
	  ,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO IS NOT NULL

--FUNÇÃO ISNULL-->ENCONTRA NULABILIDADE E PERMITE ALTERAÇÃO
SELECT CODFUN
	  ,NOME
	  ,ISNULL(SALARIO,0) AS SALARIO
FROM TB_EMPREGADO
ORDER BY SALARIO

SELECT NOME
	  ,ENDERECO
	  ,ISNULL(BAIRRO, 'NÃO INFORMADO') AS BAIRRO
FROM TB_CLIENTE
ORDER BY BAIRRO

--IIF
SELECT NOME
	  ,ENDERECO
	  ,IIF(BAIRRO= '', 'NÃO INFORMADO', ISNULL(BAIRRO, 'NAO INFORMADO')) AS BAIRRO
FROM TB_CLIENTE
ORDER BY BAIRRO
