--VARIAVEL QUE RECEBERÁ O VALOR DE UMA QUERY

DECLARE @CODIGO INT
	   ,@SALARIO NUMERIC (18,2)
SET @CODIGO=5
SET @SALARIO=(SELECT SALARIO
              FROM TB_EMPREGADO
              WHERE CODFUN=@CODIGO)

PRINT CONCAT ('SALARIO=', @SALARIO)

-----------------------------------------------------------------------
DECLARE @QTDE_REG INT
SET @QTDE_REG=(SELECT COUNT (*)
               FROM TB_EMPREGADO)
SELECT @QTDE_REG AS QTDE_REGISTROS