CREATE DATABASE SISTEMA_PEDIDOS
ON
(NAME=SISTEMAS_PEDIDOS
,FILENAME='C:\DADOS.DB\TABPEDIDOS.MDF'
,SIZE=10MB
,MAXSIZE=50MB
,FILEGROWTH=5MB
)
LOG ON
(NAME=SISPEDIDO_LOG
,FILENAME='C:\DADOS.DB\SISPEDIDO_LOG.LDF'
,SIZE=2MB
,MAXSIZE=20MB
,FILEGROWTH=5MB
)
USE SISTEMA_PEDIDOS
