USE SISTEMA_PEDIDOS
--POPULAR A TABELA TB_DEPARTAMENTO. EXISTEM DOIS TIPOS DE INSERÇÃO:
--INSERT DECLARATIVO E INSERT POSICIONAL
--INSERIR UM REGISTRO NA TB_DEPARTAMENTO
--INSERT DECLARATIVO (DECLARAR AS COLUNAS DA TABELA
/*
SINTAXE DO INSERT DECLARATIVO:
INSERT INTO <NOME_TABELA>(DECLARAR AS COLUNAS)
VALUES(<INFORMAR OS DADOS DE CADA COLUNA>)
*/

INSERT INTO TB_DEPARTAMENTO(COD_DEPTO,DEPTO)
VALUES(1,'PESSOAL')
--CONSULTAR REGISTROS NA TABELA TB_DEPARTAMENTO
SELECT *
FROM TB_DEPARTAMENTO

--INSERIR 3 REGISTROS DE UMA ÚNICA VEZ NA TABELA
INSERT INTO TB_DEPARTAMENTO
VALUES(2,'C.P.D')
     ,(3,'CONTROLE DE ESTOQUE')
     ,(4, 'COMPRAS')
SELECT *
FROM TB_DEPARTAMENTO