--MENOR SALARIO POR DEPARTAMENTO
SELECT EMP.COD_DEPTO
	  ,DEPTO.DEPTO
	  ,MIN(EMP.SALARIO) AS MENOR_SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO.DEPTO

--MAIOR SALARIO POR DEPARTAMENTO
SELECT EMP.COD_DEPTO
	  ,DEPTO.DEPTO
	  ,MAX(EMP.SALARIO) AS MENOR_SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO.DEPTO

--SOMA DO VALOR TOTAL POR CLIENTE
--FILTRO DE JAN/2016
SELECT PED.CODCLI
	  ,CLI.NOME
	  ,SUM(PED.VLR_TOTAL) AS TOTAL_PEDIDO
FROM TB_PEDIDO AS PED
INNER JOIN TB_CLIENTE AS CLI
ON PED.CODCLI=CLI.CODCLI
WHERE PED.DATA_EMISSAO BETWEEN '2016/01/01' AND '2016/31/01'
GROUP BY PED.CODCLI, CLI.NOME

--GROUP BY ALL
SELECT PED.CODCLI
	  ,CLI.NOME
	  ,SUM(PED.VLR_TOTAL) AS TOTAL_PEDIDO
FROM TB_PEDIDO AS PED
INNER JOIN TB_CLIENTE AS CLI
ON PED.CODCLI=CLI.CODCLI
WHERE PED.DATA_EMISSAO BETWEEN '2016/01/01' AND '2016/31/01'
GROUP BY ALL PED.CODCLI, CLI.NOME
ORDER BY TOTAL_PEDIDO DESC
