USE PEDIDOS

--EXIBIR O CUSTO SALARIAL POR DEPARTAMENTO
SELECT EMP.COD_DEPTO
	  ,DEPTO.DEPTO
	  ,SUM(EMP.SALARIO) AS CUSTO_SALARIAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO.DEPTO
ORDER BY CUSTO_SALARIAL DESC

--EXIBIR OS 5 DEPARTAMENTOS COM MAIOR CUSTO SALARIAL
SELECT TOP 5 EMP.COD_DEPTO
	  ,DEPTO.DEPTO
	  ,SUM(EMP.SALARIO) AS CUSTO_SALARIAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO.DEPTO
ORDER BY CUSTO_SALARIAL DESC

--CUSTO SALARIAL POR DEPARTAMENTO E CASO HAJA, OS REGISTROS NULO
SELECT EMP.COD_DEPTO
	  ,DEPTO.DEPTO
	  ,SUM(EMP.SALARIO) AS CUSTO_SALARIAL
FROM TB_EMPREGADO AS EMP
LEFT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO.DEPTO
ORDER BY CUSTO_SALARIAL DESC
