USE PEDIDOS

--FUNÇÃO DE AGREGAÇÃO
/*
SUM --> SOMA
AVG --> MEDIA
MAX --> MAIOR VALOR
MIN --> MENOR VALOR
COUN -- CONTAR
*/

SELECT AVG(SALARIO) AS MEDIA_SALARIAL
FROM TB_EMPREGADO

SELECT MIN(SALARIO) AS MENOR_SALARIO
FROM TB_EMPREGADO

SELECT MAX(SALARIO) AS MAIOR_SALARIO
FROM TB_EMPREGADO

SELECT COUNT(*) AS QTDE_REGISTROS
FROM TB_EMPREGADO


SELECT AVG(SALARIO) AS MEDIA_SALARIAL
FROM TB_EMPREGADO
WHERE COD_DEPTO=2

SELECT MIN(SALARIO) AS MENOR_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO=7

SELECT MAX(SALARIO) AS MAIOR_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO=7

SELECT MIN(SALARIO) AS MENOR_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO=3

SELECT MAX(SALARIO) AS MAIOR_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO=3

