USE PEDIDOS

SELECT EMP.COD_DEPTO
	  ,DEPTO.DEPTO
	  ,SUM(EMP.SALARIO) AS TOTAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO

--T-SQL NÃO ACEITA FUNÇÃO DE AGREGAÇÕA NA CLAUSULA WHERE
--HAVING
SELECT EMP.COD_DEPTO
	  ,DEPTO.DEPTO
	  ,SUM(EMP.SALARIO) AS TOTAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO
HAVING SUM(SALARIO)>18000

--EXIBIR MÉDIA SALARIAL POR DEPARTAMENTO
--EXIBIR SOMENTE MEDIA ACIMA QUE 2000
SELECT EMP.COD_DEPTO
	  ,DEPTO.DEPTO
	  ,AVG(EMP.SALARIO) AS MEDIA_SALARIAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO
HAVING AVG(SALARIO)>2000
ORDER BY MEDIA_SALARIAL


